---
# Per environment values which override defaults in hmpps-electronic-monitoring-create-an-order/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-electronic-monitoring-create-an-order-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://hmpps-electronic-monitoring-create-an-order-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: PRE-PRODUCTION
    AUDIT_ENABLED: "false"
    CEMO_API_URL: "https://hmpps-electronic-monitoring-create-an-order-api-preprod.hmpps.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
